#!/bin/bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hosp1.arez/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hosp1.arez/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-hosp1 --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hosp1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hosp1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hosp1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hosp1.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hosp1's CA cert to hosp1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/tlscacerts/ca.crt"

  # Copy hosp1's CA cert to hosp1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp1.arez/tlsca"
  cp "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp1.arez/tlsca/tlsca.hosp1.arez-cert.pem"

  # Copy hosp1's CA cert to hosp1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp1.arez/ca"
  cp "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp1.arez/ca/ca.hosp1.arez-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hosp1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-hosp1 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-hosp1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hosp1 --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/msp" --csr.hosts peer0.hosp1.arez --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls" --enrollment.profile tls --csr.hosts peer0.hosp1.arez --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer0.hosp1.arez/tls/server.key"

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/msp" --csr.hosts peer1.hosp1.arez --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/msp/config.yaml"

  infoln "Generating the peer1-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls" --enrollment.profile tls --csr.hosts peer1.hosp1.arez --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hosp1.arez/peers/peer1.hosp1.arez/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/users/User1@hosp1.arez/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp1.arez/users/User1@hosp1.arez/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:7054 --caname ca-hosp1 -M "${PWD}/organizations/peerOrganizations/hosp1.arez/users/Admin@hosp1.arez/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hosp1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp1.arez/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp1.arez/users/Admin@hosp1.arez/msp/config.yaml"
}

function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hosp2.rizk/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hosp2.rizk/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-hosp2 --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hosp2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hosp2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hosp2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hosp2.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hosp2's CA cert to hosp2's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/tlscacerts/ca.crt"

  # Copy hosp2's CA cert to hosp2's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp2.rizk/tlsca"
  cp "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp2.rizk/tlsca/tlsca.hosp2.rizk-cert.pem"

  # Copy hosp2's CA cert to hosp2's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hosp2.rizk/ca"
  cp "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hosp2.rizk/ca/ca.hosp2.rizk-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hosp2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-hosp2 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-hosp2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hosp2 --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/msp" --csr.hosts peer0.hosp2.rizk --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls" --enrollment.profile tls --csr.hosts peer0.hosp2.rizk --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer0.hosp2.rizk/tls/server.key"

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/msp" --csr.hosts peer1.hosp2.rizk --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/msp/config.yaml"

  infoln "Generating the peer1-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls" --enrollment.profile tls --csr.hosts peer1.hosp2.rizk --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hosp2.rizk/peers/peer1.hosp2.rizk/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/users/User1@hosp2.rizk/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp2.rizk/users/User1@hosp2.rizk/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:8054 --caname ca-hosp2 -M "${PWD}/organizations/peerOrganizations/hosp2.rizk/users/Admin@hosp2.rizk/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hosp2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hosp2.rizk/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hosp2.rizk/users/Admin@hosp2.rizk/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/eurisko

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/eurisko

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/eurisko/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/eurisko/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/eurisko/msp/tlscacerts/tlsca.eurisko-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/eurisko/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/eurisko/tlsca/tlsca.eurisko-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # infoln "Registering orderer"
  # set -x
  # fabric-ca-client register --caname ca-orderer --id.name orderer2 --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/msp" --csr.hosts orderer.eurisko --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/eurisko/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls" --enrollment.profile tls --csr.hosts orderer.eurisko --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer.eurisko/msp/tlscacerts/tlsca.eurisko-cert.pem"

  # infoln "Generating the orderer2 msp"
  # set -x
  # fabric-ca-client enroll -u https://orderer2:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/msp" --csr.hosts orderer2.eurisko --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  # cp "${PWD}/organizations/ordererOrganizations/eurisko/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/msp/config.yaml"

  # infoln "Generating the orderer-tls certificates"
  # set -x
  # fabric-ca-client enroll -u https://orderer2:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls" --enrollment.profile tls --csr.hosts orderer2.eurisko --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  # # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  # cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/ca.crt"
  # cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/server.crt"
  # cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/server.key"

  # # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  # mkdir -p "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/msp/tlscacerts"
  # cp "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/eurisko/orderers/orderer2.eurisko/msp/tlscacerts/tlsca.eurisko-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/eurisko/users/Admin@eurisko/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/eurisko/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/eurisko/users/Admin@eurisko/msp/config.yaml"
}
